export const MALAWI_DISTRICTS = [
  "Dedza",
  "Dowa",
  "Kasungu",
  "Lilongwe",
  "Mchinji",
  "Nkhotakota",
  "Ntcheu",
  "Ntchisi",
  "Salima",
  "Chitipa",
  "Karonga",
  "Likoma",
  "Mzimba",
  "Nkhata Bay",
  "Rumphi",
  "Balaka",
  "Blantyre",
  "Chikwawa",
  "Chiradzulu",
  "Machinga",
  "Mangochi",
  "Mulanje",
  "Mwanza",
  "Nsanje",
  "Thyolo",
  "Phalombe",
  "Zomba",
  "Neno",
] as const;

export const MALAWI_AREAS = [
  "Area 1",
  "Area 2",
  "Area 3",
  "Area 6",
  "Area 9",
  "Area 10",
  "Area 11",
  "Area 12",
  "Area 13",
  "Area 14",
  "Area 15",
  "Area 17",
  "Area 18",
  "Area 20",
  "Area 21",
  "Area 22",
  "Area 23",
  "Area 24",
  "Area 25",
  "Area 36",
  "Area 43",
  "Area 44",
  "Area 47",
  "Area 49",
  "Area 50",
  "Area 51",
  "Area 52",
  "Area 53",
  "Area 54",
  "Area 55",
  "Area 56",
  "Area 57",
  "Area 58",
  "Old Town",
  "City Centre",
  "Capital Hill",
  "Kanengo",
  "Kawale",
  "Biwi",
  "Mtandire",
  "Chinsapo",
  "Ngwenya",
  "Ndirande",
  "Chilomoni",
  "Bangwe",
  "Soche",
  "Chirimba",
  "Kachere",
  "Mbayani",
  "Manase",
  "Zingwangwa",
  "Machinjiri",
  "South Lunzu",
  "Nyambadwe",
  "Sunnyside",
  "Mandala",
  "Kabula",
  "Chinyonga",
  "Newlands",
  "Kanjedza",
  "Chichiri",
  "Namiwawa",
  "Limbe Central",
  "Chiwembe",
  "Chitawira",
  "Katoto",
  "Chibanja",
  "Luwinga",
  "Zolozolo",
  "Area 1A",
  "Area 1B",
  "Mzuzu University Area",
  "Chinamwali",
  "Matawale",
  "Likangala",
  "Sadzi",
  "Zomba Town Centre",
  "Domasi",
  "Mangochi Town",
  "Monkey Bay",
  "Cape Maclear",
  "Namwera",
  "Kasungu Town",
  "Salima Town",
  "Nkhotakota Boma",
  "Dedza Boma",
  "Ntcheu Boma",
  "Mchinji Boma",
  "Dowa Boma",
  "Ntchisi Boma",
  "Balaka Town",
  "Liwonde",
  "Mulanje Boma",
  "Thyolo Boma",
  "Phalombe Boma",
  "Chikwawa Boma",
  "Nsanje Boma",
  "Neno Boma",
  "Karonga Town",
  "Rumphi Boma",
  "Nkhata Bay Town",
  "Chitipa Boma",
] as const;
