export interface Database {
  public: {
    Tables: {
      profile: {
        Row: {
          id: string;
          user_id: string;
          f_name: string | null;
          gender: string | null;
          interests: string[] | null;
          profile_pic: string | null;
          picture2: string | null;
          picture3: string | null;
          city: string | null;
          area: string | null;
          dob: string | null;
          age: number | null;
          preference: string | null;
          bio: string | null;
          relationship_goals: string | null;
          pets: string | null;
          drinking: string | null;
          smoking: string | null;
          workout: string | null;
          job_title: string | null;
          company: string | null;
          zodiac: string | null;
          height: number | null;
          education: string | null;
          comu_style: string | null;
          love_style: string | null;
          partner_comu_style: string | null;
          partner_love_style: string | null;
          partner_education: string | null;
          partner_zodiac: string | null;
          lat: number | null;
          lng: number | null;
          verified: boolean | null;
          last_active_at: string | null;
          referral: string | null;
          show_ref: boolean | null;
          device: string | null;
          pause: boolean | null;
          messages_trial: number | null;
          delete: boolean | null;
          delete_me: string | null;
          email: string | null;
          phone: string | null;
          fcm_token: string | null;
          role: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          f_name?: string | null;
          gender?: string | null;
          interests?: string[] | null;
          profile_pic?: string | null;
          picture2?: string | null;
          picture3?: string | null;
          city?: string | null;
          area?: string | null;
          dob?: string | null;
          age?: number | null;
          preference?: string | null;
          bio?: string | null;
          relationship_goals?: string | null;
          pets?: string | null;
          drinking?: string | null;
          smoking?: string | null;
          workout?: string | null;
          job_title?: string | null;
          company?: string | null;
          zodiac?: string | null;
          height?: number | null;
          education?: string | null;
          comu_style?: string | null;
          love_style?: string | null;
          partner_comu_style?: string | null;
          partner_love_style?: string | null;
          partner_education?: string | null;
          partner_zodiac?: string | null;
          lat?: number | null;
          lng?: number | null;
          verified?: boolean | null;
          last_active_at?: string | null;
          referral?: string | null;
          show_ref?: boolean | null;
          device?: string | null;
          pause?: boolean | null;
          messages_trial?: number | null;
          delete?: boolean | null;
          delete_me?: string | null;
          email?: string | null;
          phone?: string | null;
          fcm_token?: string | null;
          role?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          f_name?: string | null;
          gender?: string | null;
          interests?: string[] | null;
          profile_pic?: string | null;
          picture2?: string | null;
          picture3?: string | null;
          city?: string | null;
          area?: string | null;
          dob?: string | null;
          age?: number | null;
          preference?: string | null;
          bio?: string | null;
          relationship_goals?: string | null;
          pets?: string | null;
          drinking?: string | null;
          smoking?: string | null;
          workout?: string | null;
          job_title?: string | null;
          company?: string | null;
          zodiac?: string | null;
          height?: number | null;
          education?: string | null;
          comu_style?: string | null;
          love_style?: string | null;
          partner_comu_style?: string | null;
          partner_love_style?: string | null;
          partner_education?: string | null;
          partner_zodiac?: string | null;
          lat?: number | null;
          lng?: number | null;
          verified?: boolean | null;
          last_active_at?: string | null;
          referral?: string | null;
          show_ref?: boolean | null;
          device?: string | null;
          pause?: boolean | null;
          messages_trial?: number | null;
          delete?: boolean | null;
          delete_me?: string | null;
          email?: string | null;
          phone?: string | null;
          fcm_token?: string | null;
          role?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: number;
          sender_id: string;
          receiver_id: string;
          message: string | null;
          hangout: boolean | null;
          match: boolean | null;
          unmatch: boolean;
          blocked: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          sender_id: string;
          receiver_id: string;
          message?: string | null;
          hangout?: boolean | null;
          match?: boolean | null;
          unmatch?: boolean;
          blocked?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          sender_id?: string;
          receiver_id?: string;
          message?: string | null;
          hangout?: boolean | null;
          match?: boolean | null;
          unmatch?: boolean;
          blocked?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      user_sessions: {
        Row: {
          id: number;
          created_at: string;
          updated_at: string;
          user_id: string;
          session_id: string;
          is_online: boolean;
          disconnected_at: string | null;
          device: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          session_id: string;
          is_online?: boolean;
          disconnected_at?: string | null;
          device?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          session_id?: string;
          is_online?: boolean;
          disconnected_at?: string | null;
          device?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
