create table if not exists public.user_sessions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null,
  session_id text not null,
  is_online boolean not null default true,
  disconnected_at timestamp with time zone null,
  device text null,
  constraint user_sessions_pkey primary key (id),
  constraint user_sessions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) tablespace pg_default;

create unique index if not exists user_sessions_session_id_key on public.user_sessions using btree (session_id) tablespace pg_default;
create index if not exists user_sessions_user_id_idx on public.user_sessions using btree (user_id) tablespace pg_default;

alter table public.user_sessions enable row level security;

create policy "Authenticated users can read presence"
on public.user_sessions
for select
to authenticated
using (true);

create policy "Users can insert own presence"
on public.user_sessions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own presence"
on public.user_sessions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own presence"
on public.user_sessions
for delete
to authenticated
using (auth.uid() = user_id);
